version: "3.3"
services:
  web:
    build: .
    container_name: smart-applications-group
    image: smart-applications-group:latest
    ports:
      - "6379-6385:5768"
    env_file: .env
    depends_on:
      - mysql
      - redis
    networks:
      smart_lan:

  mysql:
    image: mysql:latest
    container_name: smart-applications-group-mysql
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      smart_lan:
        ipv4_address: 172.28.1.5

volumes:
  db_data:
  redis_data:

networks:
  smart_lan:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16